### ISSUE TITLE
Add Azure credentials as repository secret for GitHub Actions

### ISSUE THREAD

**Issue by ypwong99** [vhive-serverless/STeLLAR#294]
E2E tests for experiments involving Azure deployments requires Azure credentials to be set up as a repository secret.

Steps to generate Azure credentials with an existing account:

1. Run `az login` and login with a web browser
2. Find your subscription ID and export it as a variable using `export AZURE_SUBSCRIPTION_ID={your_subscription_id}`
3. Run 
```
az ad sp create-for-rbac --name "STeLLAR GitHub Actions" --role contributor \
                         --scopes /subscriptions/$AZURE_SUBSCRIPTION_ID \
                         --sdk-auth
```
to generate credentials resembling
``` 
{
   "clientId": "<GUID>",
   "clientSecret": "<STRING>",
   "subscriptionId": "<GUID>",
   "tenantId": "<GUID>",
   "resourceManagerEndpointUrl": "<URL>"
   (...)
 }
```
4. Add the credentials in JSON format as a secret in GitHub

Reference: https://github.com/marketplace/actions/azure-login#configure-deployment-credentials

**Comment by ypwong99** [comment]
@dilinade May I also have your assistance on this? Thank you!

**Comment by kk-min** [comment]
Closed as secrets have been added to the repository.
