### ISSUE TITLE
Reduce Azure Deployment/Teardown Times

### ISSUE THREAD

**Issue by kk-min** [vhive-serverless/STeLLAR#314]
Cold start experiments in Azure seem to be taking an unusually long time (see Azure cold function run [here](https://github.com/vhive-serverless/STeLLAR/actions/runs/6386837039/job/17338087294)), up to 3 hours.

If possible, we should try to reduce this by deploying/removing them in parallel (e.g. using goroutines).

**Comment by ypwong99** [comment]
Closing this as it has been resolved by #317.
