### ISSUE TITLE
image size experiments results not showing on dashboard

### ISSUE THREAD

**Issue by kavi-99** [vhive-serverless/STeLLAR#469]
Image Size Experiments for AWS, GCR, and Azure do not consistently appear on the dashboard, unlike the Runtime/Warm-Cold invocation experiments, where this issue does not occur.
https://github.com/vhive-serverless/STeLLAR/actions/runs/10351485840

This week's run (13/8/24):

|   Image Size Experiments          | 50 MB      | 100 MB     |
|-------------|------------|------------|
| **AWS**     | ❌         | ❌         |
| **GCR**     | ✔️         | ❌         |
| **Azure**   | ✔️         | ✔️         |

#### 50 MB
![image](https://github.com/user-attachments/assets/ad77e6fa-e4e4-42ed-aec3-245528a8469c)
#### 100 MB
![image](https://github.com/user-attachments/assets/d9c61ae9-a904-4c43-b90a-913be73527ba)

### Workflow/GitHub Actions Completion:
![image](https://github.com/user-attachments/assets/4bff8df2-28f6-4129-b1fa-17375938a2d6)

**Comment by dilinade** [comment]
Fixed by https://github.com/vhive-serverless/STeLLAR/commit/7e57f24cc2778f8ec5b268a693f281c3a6f8d60f!

@kavi-99 Please check.
